var mongoose = require('mongoose');

var AboutSchema = new mongoose.Schema({
  aim: String,
  moto: String,
  policy: String,
  basicpolicy: String,
  codeofconduct: String,
  productimage: String,
  jp_aim: String,
  jp_moto: String,
  jp_policy: String,
   jp_basicpolicy: String,
   jp_codeofconduct: String,
   compliance: String,
   roadsafety: String,
   ProtectingtheEnvironment: String,
   ContributingtoSociety: String,
   ManagingInformation: String,
   SafetyandHealth: String,
   Discrimination: String,
   ProtectingPrivacy: String,
   BusinessInteractions: String,
   RelationshipwithGovernment: String,
   Communication: String,
   jp_compliance: String,
   jp_roadsafety: String,
   jp_ProtectingtheEnvironment: String,
   jp_ContributingtoSociety: String,
   jp_ManagingInformation: String,
   jp_SafetyandHealth: String,
   jp_Discrimination: String,
   jp_ProtectingPrivacy: String,
   jp_BusinessInteractions: String,
   jp_RelationshipwithGovernment: String,
   jp_Communication: String,
   jp_CompanyName: String,
   jp_Founded: String,
	jp_Headquarters: String,
	 jp_Capital: String,
	 jp_MainShareholders: String,
    jp_Area: String,
    jp_GroupEmployees: String,
   jp_MainDeliveryDestinations: String,
   CompanyName: String,
   Founded: String,
	Headquarters: String,
	 Capital: String,
	 MainShareholders: String,
    Area: String,
    GroupEmployees: String,
   MainDeliveryDestinations: String,
   jp_contactaddress: String,
   contactaddress: String,
   ph1: String,
   ph2: String,
   jp_ph1: String,
   jp_ph2: String,
   jp_email: String,
   email: String,
   updated_date: { type: Date, default: Date.now },
});

module.exports = mongoose.model('About', AboutSchema);
